Homework1: Alexey Horongziy
belovmd/it-academy-autumn-2021 pull request #20
Opened 2021-07-07 14:33 UTC by AlSurick

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-07-14 16:15 UTC, belovmd requested changes
missed sanity checks - missed tasks description

2021-07-14 16:15 UTC, belovmd commented on src/random_number.py
> +
1 line between import and code

2021-07-14 16:15 UTC, belovmd commented on src/prime_numbers.py
> +def iter_primes():
2 lines between import and code

2021-07-14 16:15 UTC, belovmd commented on src/triple_quoted_str.py
> +    bottles_of_beer = 9
no lines between constant and code

2021-07-14 16:15 UTC, belovmd commented on src/queens_problem_ex.py
> +BOARD_SIZE = 8
2 lines between constants and code

2021-07-16 20:55 UTC, AlSurick commented on src/queens_problem_ex.py
> +BOARD_SIZE = 8
Sorry, but I don't understand what I must change

2021-07-26 19:35 UTC, belovmd approved these changes
1

2021-07-26 19:35 UTC, closed without merging