Homework1: Vladimir Rovba
belovmd/it-academy-autumn-2021 pull request #26
Opened 2021-07-09 21:43 UTC by vm128

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-07-14 16:19 UTC, belovmd requested changes
failed sanity checks - missed docstrings

2021-07-14 16:19 UTC, belovmd commented on src/HomeWork1/hw1_task10.py
> +
1 line between import and code

2021-07-14 16:19 UTC, belovmd commented on src/HomeWork1/hw1_task13.py
> +import unittest
2 lines between import and code

2021-07-14 16:19 UTC, belovmd commented on src/HomeWork1/hw1_task11.py
> +bottles_of_beer = 9
we should have at least 1 line between constant and code

2021-07-16 19:29 UTC, vm128 commented on src/HomeWork1/hw1_task13.py
> +import unittest
Здесь вроде две строки между импортом и кодом. И должно же ведь быть две?

2021-07-26 19:52 UTC, belovmd commented on src/HomeWork1/hw1_task13.py
> +import unittest
it should be similar

2021-07-26 19:53 UTC, belovmd requested changes
missed tasks description
redundant code in pr - hw2

2021-08-04 09:16 UTC, belovmd reviewed
not addressed review - no docstrings, file from hw2

2021-08-04 09:16 UTC, closed without merging