Homework1: YAUHENI KACHKAYEU
belovmd/it-academy-autumn-2021 pull request #36
Opened 2021-07-11 19:56 UTC by KACHKAYEUYAUHENI

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-07-11 19:59 UTC, KACHKAYEUYAUHENI commented
homework1

2021-07-14 16:21 UTC, belovmd requested changes
failed sanity checks - wrong PR name
failed sanity checks - missed docstrings

2021-07-14 16:21 UTC, belovmd commented on src/task9.py
> +
1 line between import and code

2021-07-14 16:21 UTC, belovmd commented on src/task8.py
> +import glob
0 lines between import and code

2021-07-14 16:21 UTC, belovmd commented on src/task13.py
> +
2 lines between import and code

2021-07-14 16:21 UTC, belovmd commented on src/task10.py
> +bottles_of_beer = 9
should be at least 1 empty line between code and constant

2021-07-20 19:31 UTC, belovmd approved these changes
1

2021-07-20 19:32 UTC, closed without merging