Homework2: Mila Bendina
belovmd/it-academy-autumn-2021 pull request #43
Opened 2021-07-24 13:34 UTC by milabendina

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-07-28 16:27 UTC, milabendina commented
there are only 3 ready tasks in the 8th task, 2 left I'll do before the deadline

2021-08-15 18:51 UTC, belovmd requested changes
you can add one more advanced task for higher score

2021-08-15 18:51 UTC, belovmd commented on src/homework2/task2.py
> +punctuation_marks = '.,-;:?!'
what about `)([]` and others

2021-08-15 18:51 UTC, belovmd commented on src/homework2/task4.py
> +    else:
`elif`

2021-08-15 18:51 UTC, belovmd commented on src/homework2/task5.py
> +    n2 = n1
a, b = a+b, a

2021-08-15 18:51 UTC, belovmd commented on src/homework2/task6.py
> +    rev = (rev * 10) + (num % 10)
redundant parentheses

2021-08-15 18:51 UTC, belovmd commented on src/homework2/task7.py
> +    print('S = ', (p * (p - side_1) + (p - side_2) + (p - side_3)) ** 0.5)
wrong formula, doesn't solve task in description

2021-08-15 18:51 UTC, belovmd commented on src/homework2/task7.py
> +if side_1 + side_2 <= side_3:
not all necessary checks

2021-09-05 23:55 UTC, belovmd reviewed
missed 1 advanced task
8,5

2021-09-05 23:55 UTC, belovmd commented on src/homework2/task2.py
> +punctuation_marks = '.,-;:?!"@№#$%^&*'
string.punctuation

2021-09-05 23:55 UTC, closed without merging