Homework2 : Dmitry Makarevich
belovmd/it-academy-autumn-2021 pull request #49
Opened 2021-07-27 19:26 UTC by DzmitryMak

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-08-15 19:01 UTC, belovmd requested changes

2021-08-15 19:01 UTC, belovmd commented on src/homework2/task2.py
> +punctuation_marks = ',.!:-?№/'
what about `]);` and others

2021-08-15 19:01 UTC, belovmd commented on src/homework2/task5.py
> +        sum_ = num_s + num_f
a, b = a+b, a

2021-08-18 11:44 UTC, DzmitryMak commented on src/homework2/task2.py
> +punctuation_marks = ',.!:-?№/'
fixed

2021-08-18 11:44 UTC, DzmitryMak commented on src/homework2/task5.py
> +        sum_ = num_s + num_f
fixed

2021-09-16 21:03 UTC, belovmd approved these changes
9

2021-09-16 21:03 UTC, belovmd commented on src/homework2/task2.py
> +punctuation_marks = ',.!:-?№/[]();'
' " and others
review not addressed

2021-09-16 21:03 UTC, closed without merging