Homework3: Dmitry Makarevich
belovmd/it-academy-autumn-2021 pull request #63
Opened 2021-08-07 16:59 UTC by DzmitryMak

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-09-16 21:28 UTC, belovmd requested changes

2021-09-16 21:28 UTC, belovmd commented on src/homework3/task1.py
> +    if not num % 3 and not num % 5:
15?

2021-09-16 21:28 UTC, belovmd commented on src/homework3/task2.py
> +lst = [st[ind1] + st[ind2] for ind1 in range(2) for ind2 in range(1, 4)]
`for element in 'abcd'`?

2021-09-16 21:28 UTC, belovmd commented on src/homework3/task2.py
> +lst_num = [str(ind_1) + 'a' for ind_1 in range(1, 5)]
'1234'?

2021-09-16 21:28 UTC, belovmd commented on src/homework3/task5.py
> +for i in range(0, len(lst)):
for element in lst?

2021-09-17 20:34 UTC, DzmitryMak commented on src/homework3/task1.py
> +    if not num % 3 and not num % 5:
fixed

2021-09-17 20:34 UTC, DzmitryMak commented on src/homework3/task2.py
> +lst = [st[ind1] + st[ind2] for ind1 in range(2) for ind2 in range(1, 4)]
fixed

2021-09-17 20:34 UTC, DzmitryMak commented on src/homework3/task2.py
> +lst_num = [str(ind_1) + 'a' for ind_1 in range(1, 5)]
fixed

2021-09-17 20:34 UTC, DzmitryMak commented on src/homework3/task5.py
> +for i in range(0, len(lst)):
fixed

2021-10-24 17:54 UTC, belovmd approved these changes
9

2021-10-24 17:54 UTC, closed without merging