Homework4: Dmitry Makarevich
belovmd/it-academy-autumn-2021 pull request #81
Opened 2021-08-31 22:21 UTC by DzmitryMak

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-09-26 23:53 UTC, belovmd requested changes

2021-09-26 23:53 UTC, belovmd commented on src/homework 4/task2.py
> +    dct[lst[0]] = lst[1:]
a, *b = smth.split()

2021-09-26 23:53 UTC, belovmd commented on src/homework 4/task3.py
> +print(len(set(lst1) ^ set(lst2)), 'различных чисел в списках')
doesn't solve task in description

2021-09-26 23:53 UTC, belovmd commented on src/homework 4/task4.py
> +print(len(set(lst1) - set(lst2)), 'различных чисел в один список')
doesn't solve task in description

2021-09-26 23:53 UTC, belovmd commented on src/homework 4/task7.py
> +print('НОД =', a + b)
it's a cheat - you just don't know where is 0 and where is the result.

2021-10-05 10:57 UTC, DzmitryMak commented on src/homework 4/task7.py
> +print('НОД =', a + b)
fixed

2021-10-05 10:58 UTC, DzmitryMak commented on src/homework 4/task4.py
> +print(len(set(lst1) - set(lst2)), 'различных чисел в один список')
fixed

2021-10-05 10:58 UTC, DzmitryMak commented on src/homework 4/task3.py
> +print(len(set(lst1) ^ set(lst2)), 'различных чисел в списках')
fixed

2021-10-05 10:58 UTC, DzmitryMak commented on src/homework 4/task2.py
> +    dct[lst[0]] = lst[1:]
fixed

2021-10-24 18:43 UTC, belovmd approved these changes
9

2021-10-24 18:43 UTC, closed without merging